---

- file:
    src: https://raw.githubusercontent.com/hetznercloud/csi-driver/master/deploy/kubernetes/hcloud-csi.yml
    dest: cluster
    remote_src: yes
  run_once: yes
  delegate_to: localhost

- command: kubectl apply -f cluster/hcloud-csi.yml
  run_once: yes
  delegate_to: localhost
