---

- import_playbook: prepare.yml

- import_playbook: inventory.yml

- name: Prepare all nodes
  hosts: k8s
  vars_files:
    - vars/global.yml
  roles:

    - role: provision-hcloud
      hcloud:
        use_volumes: "{{ provisioning.use_volumes }}"
      when: 'provisioning.provider == "hcloud"'

    - role: provision-vsphere
      when: 'provisioning.provider == "vsphere"'

    - role: provision-ssh-config

    - role: volume-docker
      when: 'provisioning.use_volumes'
    - role: docker
    - role: k8s-node-prepare
  tags:
    - k8s-node-prepare

- import_playbook: cluster.yml
