---

- name: Provision nodes
  hosts: k8s
  gather_facts: no
  vars_files:
    - vars/global.yml
    - vars/hcloud/vault.yml
    - vars/hcloud/vars.yml
  roles:

    - role: provision-hcloud
      hcloud:
        use_volumes: "{{ provisioning.use_volumes }}"
      when: 'provisioning.provider == "hcloud"'

    - role: provision-vsphere
      when: 'provisioning.provider == "vsphere"'

    - role: provision-ssh-config
