---

- import_playbook: prepare.yml

- import_playbook: inventory.yml

- name: Prepare all nodes
  hosts: k8s
  vars_files:
    - vars/global.yml
  roles:

    - role: provision-hcloud
      hcloud:
        use_volumes: "{{ provisioning.use_volumes }}"
      when: 'provisioning.provider == "hcloud"'

    - role: provision-vsphere
      when: 'provisioning.provider == "vsphere"'

    - role: provision-ssh-config

    - role: volume-docker
      when: 'runtime == "docker" and provisioning.use_volumes'
    - role: docker
      when: 'runtime == "docker"'

    - role: containerd
      when: 'runtime == "containerd"'

    - role: k8s-node-prepare

    - role: k8s-cri-containerd
      when: 'runtime == "containerd"'
  tags:
    - k8s-node-prepare

- import_playbook: cluster.yml
