---

- set_fact:
    cloudflare:
      email_base64: "{{ cloudflare.email | b64encode }}"
      token_base64: "{{ cloudflare.token | b64encode }}"

- template:
    src: "{{ traefik.acme.challenge }}.yml"
    dest: cluster/
  run_once: yes
  delegate_to: localhost

- command: kubectl --kubeconfig=cluster/admin.conf apply -f cluster/{{ traefik.acme.challenge }}.yml
  run_once: yes
  delegate_to: localhost

- copy:
    src: traefik.yml
    dest: cluster/
  run_once: yes
  delegate_to: localhost

- command: kubectl apply -f cluster/traefik.yml
  run_once: yes
  delegate_to: localhost

- shell: kubectl --kubeconfig=cluster/admin.conf --namespace=kube-system create secret generic traefik-auth --from-file=<(htpasswd -nb {{ traefik.ui.username }} {{ traefik.ui.password }})
  args:
    executable: /bin/bash
  run_once: yes
  delegate_to: localhost

- template:
    src: traefik-ui.yml
    dest: cluster/
  run_once: yes
  delegate_to: localhost

- command: kubectl apply -f cluster/traefik-ui.yml
  run_once: yes
  delegate_to: localhost
