---

- name: Check for containerd socket
  stat:
    path: /var/run/containerd/containerd.sock
  become: yes
  register: containerd_sock

- include: containerd.yml
  when: 'containerd_sock.stat.exists and containerd_sock.stat.issock'
